name = input("Enter your name: ")
last_name = input("Enter your last name: ")
age = int(input("Enter your age: "))
country = input("Enter your country: ")
city = input("Enter your city: ")
favorite_language = input("Enter your favorite programming language: ")

print("\nStudent Card:")
print("Name:", name)
print("Last Name:", last_name)
print("Age:", age)
print("Country:", country)
print("City:", city)
print("Favorite Programming Language:", favorite_language)
